### ISSUE TITLE
Error with duplicate language Essence 1.3

### ISSUE THREAD

**Issue by ogabek96** [conjure-cp/conjure-notebook#12]
There is an error happening in incremental model building.
If there are two or more **language Essence 1.3**  is being run, conjure is returning an error as follows:

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/10335978/175168235-770ebc71-3fe6-4939-982f-baddd10225e9.png">

@ozgurakgun  should it be fixed in the conjure or handled in the extension side?

**Comment by ozgurakgun** [comment]
I think it's better if the extension takes care of this.
