### ISSUE TITLE
Needs multiple cells to make a new model

### ISSUE THREAD

**Issue by ChrisJefferson** [conjure-cp/conjure-notebook#30]
At the moment, to make a new model, we seem to need a cell with just `%conjure_clear`, then a new `%%conjure` cell.

Maybe `%%conjure_new`?

**Comment by ChrisJefferson** [comment]
One reason this particularly came up is with the tutorials, selecting "re-run all cells" in them breaks, but "re-run all cells" doesn't reset the current model.

I'm going to make a contraversal suggestion -- switching to `%%conjure_continue` (or `%%conjure_extend`?), to continue building up a model, and switching `%%conjure` to mean "start a fresh model". The reason to suggest that is at the moment using `%%conjure` causes weird issues whenever you "rerun all cells", due to the lack of resetting

**Comment by ozgurakgun** [comment]
Thanks for bringing this up Chris, this has been bugging me for a while.

I think it would be ideal if we had a lighter weight solution in terms of new magics. How does this sound:

`%%conjure --optional-cli-options` always creates a new model

`%%conjure + --optional-cli-options` always adds to the existing model.

Is it too subtle?

**Comment by ozgurakgun** [comment]
if `%%conjure+` is possible, that could be better as well...

**Comment by ChrisJefferson** [comment]
`%%conjure+` is nice if it works.

Could add `%%conjure+` now, leave `%%conjure` as is for now (while various models get changed here, and in other places), then change how `%%conjure` after changes have permeated around?

**Comment by ozgurakgun** [comment]
Also, the extension is versioned & has multiple releases, so I am less worried about making breaking changes. I guess we could bump the version to 0.1.0 with this as well. I shall investigate, but I have a feeling `%%conjure+` won't be possible. It would work with a space of course.

**Comment by ozgurakgun** [comment]
oooh, that's nice!

**Comment by ogabek96** [comment]
I think I was able to implement `conjure+`. Should `%%conjure` reset the state of `%%conjure+`?
<img width="642" alt="image" src="https://github.com/conjure-cp/conjure-notebook/assets/10335978/a17d67d7-343b-4b2b-a38c-f66a5e828b33">

**Comment by ozgurakgun** [comment]
also: I guess we can remove `conjure_clear` now?

**Comment by ozgurakgun** [comment]
I think this is now fixed via conjure+
